import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { ALLOW, expired, ruledOn } from './allow';
import { order, type Finding } from './finding';
import { fieldSweep } from './fields';
import { moduleSweep } from './modules';
import { ROOT, workspace } from './program';

/**
 * `pnpm sweep` — the six rituals in `CLAUDE.md`, run by a program
 * (`PASS.md` P1, 2026-09-09).
 *
 * It writes `SWEEP.md` and prints a summary. It is **a report, not a gate**,
 * for the reason `playwright.audit.config.ts` gives about the screen audit and
 * for one more of its own: three of the six passes are heuristics, and a
 * heuristic that blocks a push is a heuristic somebody will disable. The bar
 * for making it CI-blocking is written in `PASS.md` P1 — one clean run with an
 * empty allowlist delta — so a later session does not have to invent one.
 *
 * **The header says what it walked**, which is the lesson the screen audit
 * paid for: its `afterAll` wrote `report.md` unconditionally, so a filtered
 * run silently replaced the committed table with an empty one. A report that
 * cannot say how complete it is will eventually pass off a partial run as the
 * record.
 */

const PASSES = [
  { name: 'module', run: moduleSweep },
  { name: 'field', run: fieldSweep },
] as const;

function today(): string {
  // The one clock in this file, and it is a report header rather than a rule.
  // `packages/core` may not read a date; a script may, and this is why the
  // sweep lives in `scripts/` and not beside the code it walks.
  return new Date().toISOString().slice(0, 10);
}

function table(findings: readonly Finding[]): string {
  if (findings.length === 0) return '_Nothing._\n';
  const rows = findings.map((f) => `| ${f.grade} | \`${f.file}:${f.line}\` | ${f.what} |`);
  return ['| grade | where | what |', '| --- | --- | --- |', ...rows].join('\n') + '\n';
}

function main(): void {
  const started = Date.now();
  const w = workspace();
  const all: Finding[] = [];
  for (const pass of PASSES) all.push(...pass.run(w));

  const ruled = all.filter((f) => ruledOn(f.id) !== undefined);
  const live = all.filter((f) => ruledOn(f.id) === undefined).sort(order);
  const stale = expired(today());

  const lines: string[] = [];
  lines.push('# SWEEP.md — what the rituals found, run by a program');
  lines.push('');
  lines.push(`Generated by \`pnpm sweep\` on ${today()}. **Do not edit by hand.**`);
  lines.push('');
  lines.push(
    `Walked **${w.files.length} files** in ${((Date.now() - started) / 1000).toFixed(1)}s, ` +
      `over ${PASSES.length} of 6 passes. **${live.length} findings**, ` +
      `${ruled.length} absorbed by \`scripts/sweep/allow.ts\` (${ALLOW.length} rulings).`,
  );
  lines.push('');
  if (stale.length > 0) {
    lines.push('## Rulings whose reason has run out');
    lines.push('');
    for (const r of stale) lines.push(`- \`${r.id}\` — until ${r.until ?? ''}. ${r.why}`);
    lines.push('');
  }
  for (const pass of PASSES) {
    const mine = live.filter((f) => f.pass === pass.name);
    lines.push(`## ${pass.name} — ${mine.length}`);
    lines.push('');
    lines.push(table(mine));
  }

  writeFileSync(join(ROOT, 'SWEEP.md'), lines.join('\n'), 'utf8');
  console.log(`sweep: ${live.length} findings, ${ruled.length} ruled — SWEEP.md written`);
}

main();
