import { readFileSync, writeFileSync } from 'node:fs';
import { format, resolveConfig } from 'prettier';
import { fileURLToPath, URL } from 'node:url';
import { ICON_SOURCE, type IconName } from '../packages/core/src/theme/icons';

/**
 * Vendor the icons this game draws, and nothing else.
 *
 *   pnpm bake:icons-phosphor      (part of `pnpm bake`)
 *
 * Marc, 2026-08-30: *"no emojis only phosphor icons or assets."* The game's
 * whole symbol language was Unicode characters — `✚ ★ ◈ ❖ ✦ ▲ ◆ ■ ● ⬢ ◉ ✤ ▦ ▨
 * ❋ ✓ ◇ ← ✕ ▾ ♪` — which is a set of decisions every font on every phone gets
 * to overrule. A character is a request; an icon is a shape.
 *
 * ## Why a generated table rather than a dependency
 *
 * `@phosphor-icons/core` is 1512 icons per weight and this game draws
 * twenty-three. Importing the package at runtime would ship all of them, or
 * lean on tree-shaking to undo a decision we can simply not make. It is a
 * DEV dependency and this script lifts the paths we use into one file that is
 * committed — the same shape as `scripts/terrain.ts` and the baked PNGs: keep
 * the recipe beside the loaf, so a re-bake is one command and the build has
 * no network in it.
 *
 * Every Phosphor icon is a single `<path>` in a 256×256 box filled with
 * `currentColor`, so the whole vendored form is that one `d` string. That is
 * what makes this table legible rather than a blob.
 *
 * WEIGHT is part of the decision, and it is per icon (`ICON_SOURCE`): the
 * game's own vocabulary is FILL, because those marks are read at 16px on a
 * card and at hex size on a board and a hairline does not survive either
 * (Marc, 2026-08-26, on the thin `+`: *"I can clearly see the stars one, the +
 * cache not so much"*). The chrome's affordances are BOLD, because a back
 * arrow and a close cross are read at button size where an outline is
 * clearer than a slab.
 *
 * Phosphor is MIT (`node_modules/@phosphor-icons/core/LICENSE`), and the
 * licence is vendored beside the table for the same reason the paths are.
 */

const at = (p: string): string => fileURLToPath(new URL(`../${p}`, import.meta.url));
const from = (p: string): string =>
  fileURLToPath(new URL(`../node_modules/@phosphor-icons/core/${p}`, import.meta.url));

/** The one `d` in a Phosphor SVG. Throws rather than emitting a broken icon:
 *  a silently empty path is a mark that renders as nothing at all. */
function pathOf(file: string): string {
  const svg = readFileSync(from(`assets/${file}`), 'utf8');
  const paths = [...svg.matchAll(/<path[^>]*\sd="([^"]+)"/g)].map((m) => m[1]);
  if (paths.length === 0) throw new Error(`${file}: no path`);
  // A couple of Phosphor icons are two subpaths; joining them is exactly what
  // the SVG does, and `Path2D` and `<path>` both read the result the same way.
  return paths.join(' ');
}

const row = (name: IconName): string => `  '${name}': '${pathOf(ICON_SOURCE[name])}',`;

const rows = (Object.keys(ICON_SOURCE) as IconName[]).sort().map(row).join('\n');

const out = `// GENERATED by scripts/phosphor.ts — do not edit. Run \`pnpm bake\`.
//
// Phosphor Icons, MIT. See \`docs/licences/phosphor-LICENSE\`.
// Which icon each name draws, and at which weight, is decided in
// \`packages/core/src/theme/icons.ts\` — this file is only the paths.

import type { IconName } from '@theme/icons';

/** Every icon as its single 256x256 path, filled with \`currentColor\`. */
export const ICON_PATH: Readonly<Record<IconName, string>> = {
${rows}
};
`;

/*
 * Formatted by the project's OWN Prettier before it lands.
 *
 * The first two attempts had this file emit what Prettier "would" produce, and
 * both were wrong in a way that only `pnpm format:check` could see: whether a
 * long assignment breaks after its colon depends on rules it is not worth
 * reimplementing, and a generated file the formatter rewrites is a file that
 * is dirty the moment it is baked — on a repo where `format:check` is the
 * first CI gate. Asking the formatter is both shorter and correct by
 * construction.
 */
const target = at('apps/game/src/ui/icons.gen.ts');
writeFileSync(
  target,
  await format(out, { ...(await resolveConfig(target)), parser: 'typescript' }),
);
writeFileSync(at('docs/licences/phosphor-LICENSE'), readFileSync(from('LICENSE'), 'utf8'));

console.log(`phosphor: ${Object.keys(ICON_SOURCE).length} icons vendored`);
